import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import { Stickers } from "@/components/Stickers";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${spaceGrotesk.variable} antialiased min-h-screen flex flex-col items-center relative`}
      >
        <Stickers />
        <main className="w-full flex-1 flex justify-center items-center p-4 md:p-8 relative z-10">
          {children}
        </main>
      </body>
    </html>
  );
}
